import {
  getCurrentOrg,
  getProjectAnalytics,
  getSyncedPeecProject,
} from '@/lib/data';
import { getPeecStatus } from '@/app/actions/peec-sync';

export const dynamic = 'force-dynamic';

import {
  BrandShareOfVoiceCard,
  DemandSignalCard,
  EngineCoverageCard,
  PromptVisibilityCard,
  SuggestedActionsCard,
  TopUrlsCard,
} from '@/components/peec-analytics-cards';
import { RefreshPeecButton } from '@/components/refresh-peec-button';

/**
 * Dashboard = Peec project analytics. Every card maps to one signal a user
 * needs when designing an experiment (which prompts to A/B, which engines
 * to target, which URL to treat, where they stand vs competitors). The
 * experiment list itself lives at /experiments.
 */
export default async function DashboardPage() {
  // No auto-sync. Every Peec call originates from the user clicking
  // "Refresh from Peec" (RefreshPeecButton → POST /v1/peec/sync). The page
  // always renders from the cached PeecProject row written by the last
  // successful refresh; staleness and last-error are surfaced inline by the
  // status pill below so the user knows when to click refresh.
  const [org, peecStatus] = await Promise.all([getCurrentOrg(), getPeecStatus()]);
  if (!org) {
    // The (app) layout's auth gate should have redirected unauthenticated
    // requests to /login already. If we land here it's because the user
    // is signed in but somehow has no membership row — render a generic
    // empty state rather than crashing the dashboard.
    return (
      <div className="mx-auto max-w-6xl p-10">
        <h1 className="text-2xl font-semibold">No workspace yet</h1>
        <p className="mt-2 text-[color:var(--color-muted)]">
          Your account isn&apos;t attached to a workspace. Sign out and create
          a fresh account to provision one automatically.
        </p>
      </div>
    );
  }

  const [project, analytics] = await Promise.all([
    getSyncedPeecProject(org.id),
    getProjectAnalytics(org.id),
  ]);

  const connected = peecStatus?.mode === 'live';
  const pillStatus = derivePillStatus({ connected, project });

  return (
    <div className="mx-auto max-w-6xl p-6 space-y-6">
      <DashboardHeader org={org} project={project} status={pillStatus} />

      <PeecProjectPanel project={project} status={pillStatus} />

      {analytics ? (
        <>
          <section className="grid gap-4 md:grid-cols-2">
            <BrandShareOfVoiceCard
              brandTotals={analytics.brandTotals}
              ownBrand={analytics.ownBrand}
            />
            <EngineCoverageCard
              engineVisibility={analytics.engineVisibility}
              trackedModels={project?.cachedModels ?? []}
            />
          </section>

          <PromptVisibilityCard
            promptVisibility={analytics.promptVisibility}
            promptTextById={analytics.promptTextById}
          />

          <section className="grid gap-4 lg:grid-cols-[2fr,1fr]">
            <TopUrlsCard topUrls={analytics.topUrls} />
            <SuggestedActionsCard actions={analytics.actions} />
          </section>

          <DemandSignalCard searchQueries={analytics.searchQueries} />
        </>
      ) : (
        <section className="rounded-lg border border-dashed border-[color:var(--color-border)] p-8 text-center">
          <p className="font-medium">Waiting for first Peec sync</p>
          <p className="mt-1 text-sm text-[color:var(--color-muted)]">
            Connect Peec via the integrations page, then reload — analytics
            populate automatically.
          </p>
        </section>
      )}
    </div>
  );
}

type SyncedProject = NonNullable<Awaited<ReturnType<typeof getSyncedPeecProject>>>;

/**
 * Header surfaces the connected Peec project — the signal that drives every
 * card on the page. We lead with the Peec project name (not the org name)
 * because that's what the user is actually inspecting; the org is fixed
 * single-tenant context.
 *
 * The subtitle is a human-readable description of *what this project
 * tracks* (brand, topical area, competitors). We persist it on
 * `PeecProject.cachedDescription` during sync — generated by OpenAI when
 * `OPENAI_API_KEY` is set, otherwise a deterministic heuristic — so the
 * dashboard never has to fall back to leaking the upstream
 * `peec_project_id` to give the header any context. Counts and the
 * last-synced timestamp live in the panel below where they belong.
 */
function DashboardHeader({
  org,
  project,
  status,
}: {
  org: { id: string; name: string };
  project: SyncedProject | null;
  status: PillStatus;
}) {
  const title = project?.name ?? org.name;
  const subtitle = (() => {
    if (project?.cachedDescription) return project.cachedDescription;
    if (status.kind === 'disconnected') {
      return 'Peec MCP is not connected — connect it via the integrations page to populate this dashboard.';
    }
    if (project) {
      // Synced project but description not yet cached (pre-existing row from
      // before this field shipped, or first refresh hadn't returned enough
      // signal to summarise). Tell the user how to populate it without
      // leaking any internal id.
      return 'Click Refresh from Peec to generate a project summary and pull the latest analytics.';
    }
    return 'Connected to Peec MCP. Click Refresh from Peec on the panel below to pull project data.';
  })();

  return (
    <header className="flex items-end justify-between gap-6">
      <div>
        <h1 className="text-2xl font-semibold tracking-tight">{title}</h1>
        <p className="text-sm text-[color:var(--color-muted)] mt-1">{subtitle}</p>
      </div>
    </header>
  );
}

type PillStatus =
  | { kind: 'disconnected' }
  | { kind: 'live' }
  | { kind: 'stale'; ageHours: number }
  | { kind: 'error'; message: string; at: Date };

const STALE_AFTER_MS = 24 * 60 * 60 * 1000;

/**
 * Status pill state machine, evaluated server-side from the cached
 * PeecProject row. The page makes no Peec MCP calls — staleness and last
 * error are surfaced from durable state, so the pill is always honest about
 * what the user is looking at.
 *
 * Order matters:
 *   1. disconnected — no integration row trumps everything.
 *   2. error — a recorded sync failure beats staleness, because clicking
 *      Refresh again is the cure for both and the error message is more
 *      actionable than "stale".
 *   3. stale — last successful sync is > 24h old.
 *   4. live — connected, no error, fresh.
 */
function derivePillStatus({
  connected,
  project,
}: {
  connected: boolean;
  project: SyncedProject | null;
}): PillStatus {
  if (!connected) return { kind: 'disconnected' };
  if (project?.lastSyncError && project.lastSyncErrorAt) {
    return {
      kind: 'error',
      message: project.lastSyncError,
      at: new Date(project.lastSyncErrorAt),
    };
  }
  if (!project?.lastSyncedAt) return { kind: 'live' };
  const ageMs = Date.now() - new Date(project.lastSyncedAt).getTime();
  if (ageMs > STALE_AFTER_MS) {
    return { kind: 'stale', ageHours: Math.floor(ageMs / (60 * 60 * 1000)) };
  }
  return { kind: 'live' };
}

function StatusPill({ status }: { status: PillStatus }) {
  const palette: Record<PillStatus['kind'], string> = {
    live: 'bg-emerald-100 text-emerald-900',
    stale: 'bg-amber-100 text-amber-900',
    error: 'bg-red-100 text-red-900',
    disconnected: 'bg-zinc-100 text-zinc-700',
  };
  const label: Record<PillStatus['kind'], string> = {
    live: 'Live',
    stale: 'Stale',
    error: 'Sync failed',
    disconnected: 'Disconnected',
  };
  return (
    <span
      className={`inline-flex items-center rounded-full px-2 py-0.5 text-[10px] font-medium ${palette[status.kind]}`}
    >
      {label[status.kind]}
    </span>
  );
}

function PeecProjectPanel({
  project,
  status,
}: {
  project: SyncedProject | null;
  status: PillStatus;
}) {
  if (status.kind === 'disconnected' && !project) {
    return (
      <section className="rounded-lg border border-[color:var(--color-border)] p-5 bg-amber-50/50">
        <div className="flex items-baseline gap-2">
          <h2 className="font-medium">Peec MCP not connected</h2>
          <StatusPill status={status} />
        </div>
        <p className="text-sm text-[color:var(--color-muted)] mt-1">
          Use the Connect Peec dialog to authenticate. Once connected, click
          <span className="font-medium"> Refresh from Peec </span>
          on this panel to pull your project, prompts, brands, and analytics
          into the cache.
        </p>
      </section>
    );
  }
  if (!project) {
    return (
      <section className="rounded-lg border border-[color:var(--color-border)] p-5">
        <div className="flex items-start justify-between gap-3">
          <div>
            <div className="flex items-baseline gap-2">
              <h2 className="font-medium">Peec project</h2>
              <StatusPill status={status} />
            </div>
            <p className="text-sm text-[color:var(--color-muted)] mt-1">
              Connected to Peec MCP. Click refresh to pull your project, prompts,
              brands, and analytics into the cache.
            </p>
          </div>
          <RefreshPeecButton />
        </div>
      </section>
    );
  }
  const lastSyncedAt = project.lastSyncedAt
    ? new Date(project.lastSyncedAt).toLocaleString()
    : 'never';
  return (
    <section className="rounded-lg border border-[color:var(--color-border)] p-5 space-y-4">
      <div className="flex items-start justify-between gap-3">
        <div>
          <div className="flex items-baseline gap-2">
            <h2 className="font-medium">{project.name}</h2>
            <StatusPill status={status} />
          </div>
          <p className="text-xs text-[color:var(--color-muted)] mt-0.5">
            Last synced {lastSyncedAt}
            {status.kind === 'stale' && (
              <span className="text-amber-800"> · {status.ageHours}h ago — click refresh</span>
            )}
          </p>
          {status.kind === 'error' && (
            <p className="mt-1 text-xs text-red-700 max-w-prose">
              Last refresh ({status.at.toLocaleString()}): {status.message}
            </p>
          )}
        </div>
        <RefreshPeecButton size="sm" variant="outline" />
      </div>
      <dl className="grid grid-cols-2 sm:grid-cols-4 gap-3 text-xs">
        <Field label="Prompts" value={project.cachedPromptCount} />
        <Field label="Brands" value={project.cachedBrandCount} />
        <Field label="Models" value={project.cachedModels.length} />
        <Field label="Topics" value={topicTagCount(project.cachedTopics)} />
      </dl>
    </section>
  );
}

function topicTagCount(payload: unknown): number {
  if (!payload || typeof payload !== 'object') return 0;
  const rows = (payload as { rows?: unknown[] }).rows;
  return Array.isArray(rows) ? rows.length : 0;
}

function Field({ label, value }: { label: string; value: number }) {
  return (
    <div>
      <dt className="text-[10px] uppercase tracking-wider text-[color:var(--color-muted)]">
        {label}
      </dt>
      <dd className="font-medium text-sm tabular-nums">{value}</dd>
    </div>
  );
}
